CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE supertype AS ENUM ('POKEMON','TRAINER','ENERGY');
CREATE TYPE subtype AS ENUM (
  'BASIC','EX','TERA_EX',
  'ITEM','SUPPORTER','STADIUM',
  'BASIC_ENERGY','SPECIAL_ENERGY'
);
CREATE TYPE rarity_tier AS ENUM (
  'COMMON','UNCOMMON','RARE',
  'ILLUSTRATION_RARE','ULTRA_RARE','SECRET_RARE'
);
CREATE TYPE visual_variant AS ENUM (
  'STANDARD','REVERSE_HOLO','PROMO','ALTERNATE_ART','RAINBOW_RARE'
);
CREATE TYPE card_condition AS ENUM (
  'MINT','NEAR_MINT','LIGHTLY_PLAYED','PLAYED','HEAVILY_PLAYED','DAMAGED'
);
CREATE TYPE price_source AS ENUM ('TCGPLAYER','SCRAPED','MANUAL');
